// Copyright 2021 The gqlp Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Disk struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Tags        []string `json:"tags"`
	Description string   `json:"description"`
	Size        int      `json:"size"`
}

type MutationResult struct {
	Success bool `json:"success"`
}

type Server struct {
	ID               string   `json:"id"`
	Name             string   `json:"name"`
	Tags             []string `json:"tags"`
	Description      string   `json:"description"`
	Availability     string   `json:"availability"`
	HostName         string   `json:"hostName"`
	InterfaceDriver  string   `json:"interfaceDriver"`
	PlanID           string   `json:"planID"`
	PlanName         string   `json:"planName"`
	CPU              int      `json:"cpu"`
	Memory           int      `json:"memory"`
	Commitment       string   `json:"commitment"`
	PlanGeneration   int      `json:"planGeneration"`
	InstanceHostName string   `json:"instanceHostName"`
	InstanceStatus   string   `json:"instanceStatus"`
	Disks            []*Disk  `json:"disks"`
}

type ShutdownOption struct {
	Force bool `json:"force"`
}
